@startuml


package "REA" {
    [Preview]
    [Output Invoices]
    [Manage Layouts]
    [Migration]
}

:User: -> [Invoice Calculation]
[Invoice Calculation] -down-> [Output Invoices]
[Invoice Calculation] -down-> [Preview]
[Invoice Calculation] -down-> [Manage Layouts]
[Preview] -> [Output Invoices]
[Output Invoices] -down-> [Printer]
[Output Invoices] -down-> [DMS]


note bottom of REA: our fancy new app
note right of [Invoice Calculation]: legacy stuff

@enduml